/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.strategyy.view;

import com.mycompany.strategyy.controller.ControladorJuego;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author melissa
 */
public class JuegoFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JuegoFrame.class.getName());
    
    private ControladorJuego controlador; 
    // Dos paneles, porque J1 y J2 tienen vistas diferentes
    private PanelJugador panelJugador1Real;
    private PanelJugador panelJugador2Real;
    
    public JuegoFrame() {
        controlador = ControladorJuego.getInstancia();
        controlador.inicializarJuego();
        
        
        initComponents(); 

        // Agregar observador para actualizar la vista cuando cambie el modelo
        VistaObserver observer = new VistaObserver(this);
        controlador.agregarObservador(observer);
        
        inicializarPaneles();
        configurarVentana();
    }
    public ControladorJuego getControlador() {
        return controlador;
    }
    
    public void mostrarGanador(com.mycompany.strategyy.model.Jugador ganador) {
        String mensaje = ganador.getNombre() + " ha ganado\nVida restante: " + ganador.getVida();
        int opcion = JOptionPane.showConfirmDialog(
            this,
            mensaje + "\n¿Deseas jugar otra vez?",
            "Fin del juego",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Reiniciar el juego y actualizar la UI
            controlador.inicializarJuego();
            inicializarPaneles();
            actualizarVista();
        } else {
            // Sólo mostrar el mensaje de que el juego termino 
            JOptionPane.showMessageDialog(this, mensaje, "Fin del juego", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // Actualizar la vista completa
    public void actualizarVista() {
        panelJugador1Real.actualizar();
        panelJugador2Real.actualizar();
    }
    
    // Inicializar los paneles
    private void inicializarPaneles() {
        // Limpiar los paneles vacíos que se generan por NetBeans
        plnJugador1.removeAll();
        plnJugador2.removeAll();
        
        // Se crean paneles para cada jugador con su respectivo modelo 
        panelJugador1Real = new PanelJugador(controlador.getJugador1(), true, this);
        panelJugador2Real = new PanelJugador(controlador.getJugador2(), false, this);
        
        plnJugador1.setOpaque(true);
        plnJugador2.setOpaque(true);
        panelJugador1Real.setOpaque(true);
        panelJugador2Real.setOpaque(true);
        
        
        
        // Configurar layout y agregar los paneles
        plnJugador1.setLayout(new BorderLayout());
        plnJugador1.add(panelJugador1Real, BorderLayout.CENTER);
        
        plnJugador2.setLayout(new BorderLayout());
        plnJugador2.add(panelJugador2Real, BorderLayout.CENTER);
        
        // Refrescar los paneles
        plnJugador1.revalidate();
        plnJugador1.repaint();
        plnJugador2.revalidate();
        plnJugador2.repaint();
    }
    
  
    private void configurarVentana() {
        setTitle("Fighting Game - Strategy Pattern");
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnJugador1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAtacarse = new javax.swing.JButton();
        plnJugador2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnReasignarJ1 = new javax.swing.JButton();
        btnReasignarJ2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plnJugador1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Jugador1");

        javax.swing.GroupLayout plnJugador1Layout = new javax.swing.GroupLayout(plnJugador1);
        plnJugador1.setLayout(plnJugador1Layout);
        plnJugador1Layout.setHorizontalGroup(
            plnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnJugador1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        plnJugador1Layout.setVerticalGroup(
            plnJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnJugador1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(619, Short.MAX_VALUE))
        );

        btnAtacarse.setBackground(new java.awt.Color(255, 204, 153));
        btnAtacarse.setText("Atacarse");
        btnAtacarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarseActionPerformed(evt);
            }
        });

        plnJugador2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setText("Jugador2");

        javax.swing.GroupLayout plnJugador2Layout = new javax.swing.GroupLayout(plnJugador2);
        plnJugador2.setLayout(plnJugador2Layout);
        plnJugador2Layout.setHorizontalGroup(
            plnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnJugador2Layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(230, 230, 230))
        );
        plnJugador2Layout.setVerticalGroup(
            plnJugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnJugador2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReasignarJ1.setBackground(new java.awt.Color(255, 204, 153));
        btnReasignarJ1.setText("Reasignar J1");
        btnReasignarJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReasignarJ1ActionPerformed(evt);
            }
        });

        btnReasignarJ2.setBackground(new java.awt.Color(255, 204, 153));
        btnReasignarJ2.setText("ReasignarJ2");
        btnReasignarJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReasignarJ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plnJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtacarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReasignarJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReasignarJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plnJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(btnAtacarse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnReasignarJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReasignarJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plnJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plnJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReasignarJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReasignarJ1ActionPerformed
        // Reasignar artes del jugador 1
        controlador.reasignarArtes(controlador.getJugador1());
        actualizarVista();
    }//GEN-LAST:event_btnReasignarJ1ActionPerformed

    private void btnReasignarJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReasignarJ2ActionPerformed
        controlador.reasignarArtes(controlador.getJugador2());
        actualizarVista();
    }//GEN-LAST:event_btnReasignarJ2ActionPerformed

    private void btnAtacarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarseActionPerformed
        // Si el jugador 1 no ha generado un combo, el ataque central no se realizará
        if (panelJugador1Real != null && panelJugador1Real.tieneComboGenerado()) {
            // Guardar marca de tiempo antes de ejecutar el combo. Si durante la
            // ejecución se reinicia el juego (por ejemplo por el diálogo de
            // ganador), la marca de inicialización cambiará y evitaremos que
            // J2 ejecute su ataque en la nueva partida.
            long antesInit = controlador.getUltimaInicializacionMillis();

            // Ejecutar el combo generado por J1
            panelJugador1Real.usarCombo();

            // Si no hubo reinicio durante la ejecución y no hay ganador,
            // permitir que J2 responda aleatoriamente.
            boolean reinicioDuranteCombo = controlador.getUltimaInicializacionMillis() != antesInit;
            if (!reinicioDuranteCombo && !controlador.hayGanador()) {
                controlador.jugador2AtacaAleatorio();
            }

            actualizarVista();
        } else {
            JOptionPane.showMessageDialog(this, "El Jugador 1 no ha seleccionado un combo aún.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAtacarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new JuegoFrame().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacarse;
    private javax.swing.JButton btnReasignarJ1;
    private javax.swing.JButton btnReasignarJ2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel plnJugador1;
    private javax.swing.JPanel plnJugador2;
    // End of variables declaration//GEN-END:variables

}
